template:
  volumes:
  - name: emptydata
    storageType: EmptyDir
  containers:
  - image: crazure101daydemoce001.azurecr.io/sample:${{ env.GIT_SHA }}
    name: sample
    volumeMounts:
    - mountPath: "/data"
      volumeName: emptydata
    resources:
      cpu: 0.5
      memory: 1Gi
  initContainers: null
  scale:
    maxReplicas: 2
    minReplicas: 1
    rules:
    - name: httpscalingrule
      custom:
        type: http
        metadata:
          concurrentRequests: '50'