name: Deploy app to Azure Container Apps

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        required: true
        type: string
      ACR:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      TAG:
        required: true
        type: string
    secrets:
      ACR_USERNAME:
        required: true
      ACR_PASSWORD:
        required: true

env:
  FULL_IMAGE_NAME: ${{ inputs.ACR }}/${{ inputs.IMAGE_NAME }}:${{ inputs.TAG }}

jobs:
  build-app:
    name: Build app and push docker image to Azure Container Registry
    runs-on: ubuntu-latest
    
    steps:
      - id: checkout
        name: Checkout GitHub repository
        uses: actions/checkout@v3
      
      - id: login-acr
        name: Log in Azure Container Registry (ACR)
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.ACR }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - id: build-image
        name: Build docker image
        run: |
          docker build . -t ${{ env.FULL_IMAGE_NAME }}
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

      - id: push-image
        name: Push docker image to ACR
        run: |
          docker push ${{ env.FULL_IMAGE_NAME }}
        working-directory: ${{ inputs.WORKING_DIRECTORY }}