name: Deploy app to Azure Container Apps

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        required: true
        type: string
      ACR:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      TAG:
        required: true
        type: string
      CONTAINER_APP_NAME:
        required: true
        type: string
      RESOURCE_GROUP:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true

env:
  PORT: 8000
  INGRESS: external
  FULL_IMAGE_NAME: ${{ inputs.ACR }}/${{ inputs.IMAGE_NAME }}:${{ inputs.TAG }}

jobs:
  deploy-app:
    name: Deploy App to Azure Container Apps
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v3
    
    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create directories for template.yml
      run: |
        mkdir -p app/backend/config/containerapps

    - name: Generate template.yml with dynamic GIT_SHA
      run: |
        cat <<EOF > app/backend/config/containerapps/template.yml
        template:
          volumes:
          - name: emptydata
            storageType: EmptyDir
          containers:
          - image: ${{ env.FULL_IMAGE_NAME }}
            name: ca-azure101day-demo-ce-001
            volumeMounts:
            - mountPath: "/data"
              volumeName: emptydata
            resources:
              cpu: 0.5
              memory: 1Gi
          initContainers: null
          scale:
            maxReplicas: 2
            minReplicas: 1
            rules:
            - name: httpscalingrule
              custom:
                type: http
                metadata:
                  concurrentRequests: '50'
        EOF
    
    - name: Deploy image To Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        containerAppName: ${{ inputs.CONTAINER_APP_NAME }}
        resourceGroup: ${{ inputs.RESOURCE_GROUP }}
        imageToDeploy: ${{ env.FULL_IMAGE_NAME }}
        targetPort: ${{ env.PORT }}
        ingress: ${{ env.INGRESS }}
        environmentVariables: "DATA_DIR=/data"
        yamlConfigPath: ${{ inputs.WORKING_DIRECTORY }}/config/containerapps/template.yml