name: Test Backend API

on:
  workflow_call:
    secrets:
      PROJECT_CONNECTION_STRING:
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_TENANT_ID:
        required: true
  
jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PROJECT_CONNECTION_STRING: ${{ secrets.PROJECT_CONNECTION_STRING }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Install dependencies
      run: |
        cd app/backend/api
        ~/.local/bin/poetry install --no-root

    - name: Create data directory
      run: |
        sudo mkdir -p /data
        sudo chmod -R 777 /data

    - name: Run tests      
      run: |
        cd app/backend/api
        ~/.local/bin/poetry run pytest tests
        ~/.local/bin/poetry run pytest --cov=src --cov-report=term-missing