name: Build and deploy backend app to dev

on:
  push:

jobs:
  build-workflow:
    uses: ./.github/workflows/common_build.yml
    with:
      WORKING_DIRECTORY: app/backend
      ACR: crazure101daydemoce001.azurecr.io
      IMAGE_NAME: sample
      TAG: ${{ github.sha }}
    secrets:
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  
  deploy-workflow:
    needs: build-workflow
    uses: ./.github/workflows/common_deploy.yml
    with:
      WORKING_DIRECTORY: app/backend
      ACR: crazure101daydemoce001.azurecr.io
      IMAGE_NAME: sample
      TAG: ${{ github.sha }}
      CONTAINER_APP_NAME: ca-azure101day-demo-ce-001
      RESOURCE_GROUP: rg-azure101day-demo-canadaeast-001
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CRED }}